USE ESTUDO_INDICE
GO

SELECT PRIMEIRO_NOME, ULTIMO_NOME FROM ESTUDANTES WHERE PRIMEIRO_NOME = 'Ali'
GO
SELECT PRIMEIRO_NOME, ULTIMO_NOME FROM ESTUDANTES WHERE ULTIMO_NOME = 'Hadi'

DROP INDEX IDX_UN_PN ON ESTUDANTES

SELECT 
	 PRIMEIRO_NOME
	,ULTIMO_NOME 
FROM 
	ESTUDANTES 
WHERE 
	PRIMEIRO_NOME LIKE '%1'
ORDER BY
	 PRIMEIRO_NOME ASC
	,ULTIMO_NOME DESC

GO
CREATE INDEX IX_EST_PN_UN ON ESTUDANTES(PRIMEIRO_NOME ASC, ULTIMO_NOME DESC)

ALTER INDEX IX_EST_PN_UN ON ESTUDANTES REBUILD WITH (FILLFACTOR = 90)
GO

SELECT TOP 5000 * FROM ESTUDANTES WHERE ID < 5000 ORDER BY PRIMEIRO_NOME ASC

SELECT TOP 5000 * FROM ESTUDANTES WHERE ID < 5000 ORDER BY ULTIMO_NOME DESC

SELECT TOP 5000 * FROM ESTUDANTES WHERE ID < 5000 ORDER BY ID ASC